### ISSUE TITLE
Color picker's saturation property works wrong in dark areas

### ISSUE THREAD

**Issue by ceremcem** [dagnelies/ractive-examples#1]
I would expect the circle stay intact while I'm changing the saturation value: 

![peek 2018-05-16 18-18](https://user-images.githubusercontent.com/6639874/40126523-32bba836-5936-11e8-81b6-c8fcb1466c40.gif)

**Comment by dagnelies** [comment]
It's basically just a wrapper of https://rakujira.jp/projects/iro/

You can simply use the `wheelLightness` flag, like:

    <color-picker color="{{myColor}}" width="200" height="200" wheelLightness="false" />

**Comment by ceremcem** [comment]
A fast closed bug.
